local colors = {
    Normal = { fg = "#E0E2EB", bg = "#272120" },
    Bold = { bold = true },
    Boolean = { fg = "#F28F0D" },
    Breakpoint = { fg = "#FF4D4D", bg = "#1F1A19" },
    BreakpointCurrent = { fg = "#FF4D4D", bg = "#514543" },
    Character = { fg = "#FCAC8D" },
    ColorColumn = { bg = "#2B1717" },
    Comment = { fg = "#656A81" },
    Constant = { fg = "#F28F0D" },
    Cursor = { reverse = true },
    CursorBorder = { fg = "#E0E2EB", bg = "#241F1E" },
    CursorColumn = { bg = "#1F1A19" },
    CursorLine = { bg = "#3B3230" },
    CursorLineNr = { bg = "#514543" },
    DapStopped = { fg = "#FF4D4D", bg = "#1F1A19" },
    DapStoppedCurrent = { fg = "#FF4D4D", bg = "#514543" },
    Delimiter = { fg = "#B9BDD0" },
    DiagnosticError = { fg = "#FF4D4D" },
    DiagnosticFloatingError = { fg = "#FF4D4D" },
    DiagnosticFloatingHint = { fg = "#67E4A8" },
    DiagnosticFloatingInfo = { fg = "#8FFDFF" },
    DiagnosticFloatingWarn = { fg = "#FFE866" },
    DiagnosticHint = { fg = "#67E4A8" },
    DiagnosticInfo = { fg = "#8FFDFF" },
    DiagnosticSignError = { fg = "#FF4D4D" },
    DiagnosticSignHint = { fg = "#67E4A8" },
    DiagnosticSignInfo = { fg = "#8FFDFF" },
    DiagnosticSignWarn = { fg = "#FFE866" },
    DiagnosticUnderlineError = { sp = "#FF4D4D", undercurl = true },
    DiagnosticUnderlineHint = { sp = "#67E4A8", undercurl = true },
    DiagnosticUnderlineInfo = { sp = "#8FFDFF", undercurl = true },
    DiagnosticUnderlineWarn = { sp = "#FFE866", undercurl = true },
    DiagnosticUnnecessary = { fg = "#81869C" },
    DiagnosticVirtualTextError = { fg = "#FF4D4D" },
    DiagnosticVirtualTextHint = { fg = "#67E4A8" },
    DiagnosticVirtualTextInfo = { fg = "#8FFDFF" },
    DiagnosticVirtualTextWarn = { fg = "#FFE866" },
    DiagnosticWarn = { fg = "#FFE866" },
    Directory = { fg = "#6ABFFB" },
    Float = { fg = "#F28F0D" },
    Function = { fg = "#33AAFF" },
    Identifier = { fg = "#99CFFF" },
    LineNr = { fg = "#B1A3A0" },
    LspInlayHint = { fg = "#B2B4BD", bg = "#3B3230" },
    LspSignatureActiveParameter = { fg = "#E0E2EB", bg = "#524D4C" },
    NormalFloat = { fg = "#E0E2EB", bg = "#272120" },
    Number = { fg = "#F28F0D" },
    Operator = { fg = "#B9BDD0" },
    Pmenu = { fg = "#E0E2EB", bg = "#322B29" },
    PmenuSbar = { bg = "#161312" },
    PmenuSel = { fg = "#E0E2EB", bg = "#705F5C" },
    PmenuThumb = { bg = "#4C403E" },
    Search = { fg = "#272120", bg = "#ECC413" },
    Special = { fg = "#B9BDD0" },
    ["@lsp.type.formatSpecifier"] = { link = "Special" },
    Statement = { fg = "#FF61B5" },
    StatusLine = { fg = "#E0E2EB", bg = "#161312" },
    StatusLineNC = { fg = "#272120", bg = "#E0E2EB" },
    String = { fg = "#FB8151" },
    TodoBgFIX = { fg = "#272120", bg = "#FF4D4D", bold = true },
    TodoBgNOTE = { fg = "#272120", bg = "#1EA7A9", bold = true },
    TodoBgTEST = { fg = "#272120", bg = "#67E4A8", bold = true },
    TodoBgTODO = { fg = "#272120", bg = "#8FFDFF", bold = true },
    TodoBgWARN = { fg = "#272120", bg = "#FFE866", bold = true },
    TodoFgFIX = { fg = "#FF4D4D" },
    TodoFgNOTE = { fg = "#1EA7A9" },
    TodoFgTEST = { fg = "#67E4A8" },
    TodoFgTODO = { fg = "#8FFDFF" },
    TodoFgWARN = {},
    Type = { fg = "#00C777" },
    Underlined = { underline = true },
    Visual = { fg = "#E0E2EB", bg = "#574A47" },
    ["@constant.builtin"] = { fg = "#F28F0D" },
    ["@constant.macro"] = { fg = "#33AAFF" },
    ["@float"] = { fg = "#F28F0D" },
    ["@keyword.directive"] = { fg = "#CC94B2" },
    ["@label"] = { fg = "#FFD1EA" },
    ["@lsp.type.builtinType"] = { fg = "#00C777" },
    ["@lsp.type.decorator"] = { fg = "#EABA7B" },
    ["@lsp.type.enumMember"] = { fg = "#00F593" },
    ["@lsp.type.interface"] = { fg = "#97EDCA" },
    ["@lsp.type.namespace"] = { fg = "#EABA7B" },
    ["@lsp.type.selfKeyword"] = { fg = "#FF7070" },
    ["@macro"] = { fg = "#33AAFF" },
    ["@tag"] = { fg = "#FF61B5" },
    ["@tag.attribute"] = { fg = "#99D5FF" },
    ["@tag.delimiter"] = { fg = "#99CFFF" },
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
