local colors = {
    Normal                        = { fg = "#E0E2EB", bg = "#0F161F" },
    BlinkCmpDoc                   = { bg = "#172230" },
    BlinkCmpDocBorder             = { bg = "#172230" },
    BlinkCmpDocSeparator          = { bg = "#172230" },
    BlinkCmpSignatureHelp         = { bg = "#172230" },
    Bold                          = { bold = true },
    Boolean                       = { fg = "#F28F0D" },
    Breakpoint                    = { fg = "#FF4D4D", bg = "#0C1118" },
    BreakpointCurrent             = { fg = "#FF4D4D", bg = "#283A53" },
    Character                     = { fg = "#FCAC8D" },
    ColorColumn                   = { bg = "#2B1717" },
    Comment                       = { fg = "#656A81" },
    Constant                      = { fg = "#F28F0D" },
    CurSearch                     = { fg = "#0F161F", bg = "#F7E7A1" },
    CursorBorder                  = { fg = "#E0E2EB", bg = "#0D131C" },
    CursorColumn                  = { bg = "#0C1118" },
    CursorLine                    = { bg = "#1B2737" },
    CursorLineNr                  = { bg = "#283A53" },
    DapStopped                    = { fg = "#FF4D4D", bg = "#0C1118" },
    DapStoppedCurrent             = { fg = "#FF4D4D", bg = "#283A53" },
    Delimiter                     = { fg = "#B9BDD0" },
    DiagnosticError               = { fg = "#FF4D4D" },
    DiagnosticFloatingError       = { fg = "#FF4D4D" },
    DiagnosticFloatingHint        = { fg = "#67E4A8" },
    DiagnosticFloatingInfo        = { fg = "#8FFDFF" },
    DiagnosticFloatingWarn        = { fg = "#FFE866" },
    DiagnosticHint                = { fg = "#67E4A8" },
    DiagnosticInfo                = { fg = "#8FFDFF" },
    DiagnosticSignError           = { fg = "#FF4D4D" },
    DiagnosticSignHint            = { fg = "#67E4A8" },
    DiagnosticSignInfo            = { fg = "#8FFDFF" },
    DiagnosticSignWarn            = { fg = "#FFE866" },
    DiagnosticUnderlineError      = { sp = "#FF4D4D", undercurl = true },
    DiagnosticUnderlineHint       = { sp = "#67E4A8", undercurl = true },
    DiagnosticUnderlineInfo       = { sp = "#8FFDFF", undercurl = true },
    DiagnosticUnderlineWarn       = { sp = "#FFE866", undercurl = true },
    DiagnosticUnnecessary         = { fg = "#81869C" },
    DiagnosticVirtualTextError    = { fg = "#FF4D4D" },
    DiagnosticVirtualTextHint     = { fg = "#67E4A8" },
    DiagnosticVirtualTextInfo     = { fg = "#8FFDFF" },
    DiagnosticVirtualTextWarn     = { fg = "#FFE866" },
    DiagnosticWarn                = { fg = "#FFE866" },
    DiffAdd                       = { fg = "#0F161F", bg = "#67E4A8" },
    DiffChange                    = { fg = "#0F161F", bg = "#8FFDFF" },
    DiffDelete                    = { fg = "#0F161F", bg = "#FF4D4D" },
    DiffText                      = { fg = "#0F161F", bg = "#8FFDFF" },
    Directory                     = { fg = "#6ABFFB" },
    Float                         = { fg = "#F28F0D" },
    FloatBorder                   = { fg = "#E0E2EB", bg = "#0F161F" },
    Function                      = { fg = "#33AAFF" },
    Identifier                    = { fg = "#99CFFF" },
    IncSearch                     = { fg = "#0F161F", bg = "#F7E7A1" },
    LineNr                        = { fg = "#839FC3" },
    LspInlayHint                  = { fg = "#B2B4BD", bg = "#1B2737" },
    LspSignatureActiveParameter   = { fg = "#E0E2EB", bg = "#3B444E" },
    MiniFilesBorder               = { fg = "#E0E2EB" },
    MiniFilesBorderModified       = { fg = "#FFE866" },
    MiniFilesNormal               = { bg = "#0F161F" },
    MiniFilesTitle                = { fg = "#E0E2EB" },
    MiniFilesTitleFocused         = { fg = "#E0E2EB", bold = true },
    MiniIndentscopeSymbol         = { fg = "#727AA1" },
    MiniJump2dSpot                = { fg = "#0F161F", bg = "#E0E2EB" },
    MiniNotifyBorder              = { fg = "#E0E2EB", bg = "#0F161F" },
    MiniNotifyNormal              = { fg = "#E0E2EB", bg = "#0F161F" },
    MiniNotifyTitle               = { fg = "#E0E2EB", bg = "#0F161F", bold = true },
    NormalFloat                   = { fg = "#E0E2EB", bg = "#172230" },
    Number                        = { fg = "#F28F0D" },
    Operator                      = { fg = "#B9BDD0" },
    PmenuSbar                     = { bg = "#080C11" },
    PmenuSel                      = { fg = "#E0E2EB", bg = "#3C587C" },
    PmenuThumb                    = { bg = "#26384F" },
    Search                        = { fg = "#0F161F", bg = "#ECC413" },
    SnacksPicker                  = { fg = "#E0E2EB", bg = "#0F161F" },
    Special                       = { fg = "#B9BDD0" },
    ["@lsp.type.formatSpecifier"] = { link = "Special" },
    Statement                     = { fg = "#FF4DB5" },
    StatusLine                    = { fg = "#E0E2EB", bg = "#080C11" },
    StatusLineNC                  = { fg = "#0F161F", bg = "#E0E2EB" },
    String                        = { fg = "#FB8151" },
    Substitute                    = { fg = "#0F161F", bg = "#ECC413" },
    TodoBgFIX                     = { fg = "#0F161F", bg = "#FF4D4D", bold = true },
    TodoBgNOTE                    = { fg = "#0F161F", bg = "#1EA7A9", bold = true },
    TodoBgTEST                    = { fg = "#0F161F", bg = "#67E4A8", bold = true },
    TodoBgTODO                    = { fg = "#0F161F", bg = "#8FFDFF", bold = true },
    TodoBgWARN                    = { fg = "#0F161F", bg = "#FFE866", bold = true },
    TodoFgFIX                     = { fg = "#FF4D4D" },
    TodoFgNOTE                    = { fg = "#1EA7A9" },
    TodoFgTEST                    = { fg = "#67E4A8" },
    TodoFgTODO                    = { fg = "#8FFDFF" },
    TodoFgWARN                    = {},
    Type                          = { fg = "#14B82A" },
    Underlined                    = { underline = true },
    Visual                        = { fg = "#E0E2EB", bg = "#2D425D" },
    WhichKey                      = { fg = "#E0E2EB", bg = "#0F161F" },
    WhichKeyDesc                  = { fg = "#6ABFFB", bg = "#0F161F" },
    WhichKeyGroup                 = { fg = "#FF4DB5", bg = "#0F161F" },
    WhichKeyNormal                = { fg = "#E0E2EB", bg = "#0F161F" },
    ["@constant.builtin"]         = { fg = "#F28F0D" },
    ["@constant.macro"]           = { fg = "#33AAFF" },
    ["@float"]                    = { fg = "#F28F0D" },
    ["@keyword.directive"]        = { fg = "#F3AAD5" },
    ["@label"]                    = { fg = "#F3AAD5" },
    ["@lsp.type.builtinType"]     = { fg = "#14B82A" },
    ["@lsp.type.decorator"]       = { fg = "#EABA7B" },
    ["@lsp.type.enumMember"]      = { fg = "#17D375" },
    ["@lsp.type.interface"]       = { fg = "#A0E4A9" },
    ["@lsp.type.namespace"]       = { fg = "#EABA7B" },
    ["@lsp.type.selfKeyword"]     = { fg = "#FF7070" },
    ["@macro"]                    = { fg = "#33AAFF" },
    ["@tag"]                      = { fg = "#FF4DB5" },
    ["@tag.attribute"]            = { fg = "#99D5FF" },
    ["@tag.delimiter"]            = { fg = "#99CFFF" },
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
