pulse.rules = [
  {
    # pactl list sink-inputs | grep -E "application\.(name|process\.binary)"
    matches = [ { application.process.binary = "zen-bin" } ]
    actions = {
      update-props = {
        target.object = "wavelink-browser"
      }
    }
  }
  {
    matches = [ { application.process.binary = "spotify" } ]
    actions = {
      update-props = {
        target.object = "wavelink-music"
      }
    }
  }
  {
    matches = [ 
      { application.process.binary = "discord" }
    ]
    actions = {
      update-props = {
        target.object = "wavelink-voice-chat"
      }
    }
  }
  {
    # Example for games
    matches = [ { application.process.binary = "cs2" } ]
    actions = {
      update-props = {
        target.object = "wavelink-games"
      }
    }
  }
]
